[package]
name = "database-test"
version = "0.1.0"
authors = ["whatasoda <git@whatasoda.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3.1"
num-integer = "0.1.44"
num-traits = "0.2"
